default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres
  password: example

development:
  primary: &primary_development
    <<: *default
    database: konitagious_development
    port: 5432
  queue:
    <<: *primary_development
    database: konitagious_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: konitagious_test
  port: 5432

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV["POSTGRES_HOST"] %>
    database: <%= ENV["POSTGRES_DB"] %>
    username: <%= ENV["POSTGRES_USER"] %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    port: <%= ENV["POSTGRES_PORT"] %>
  queue:
    <<: *primary_production
    database: konitagious_production_queue
    migrations_paths: db/queue_migrate
  cache:
    <<: *primary_production
    database: konitagious_production_cache
    migrations_paths: db/cache_migrate
  cable:
    <<: *primary_production
    database: konitagious_production_cable
    migrations_paths: db/cable_migrate